import { useState } from 'react';
import { ArrowDown, ArrowRight, BarChart3, Bot, CalendarDays, Check, Menu, Mic, Play, Send, X } from 'lucide-react';

const roomImage = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Image%20Gen%202026-08-15%20from%20ChatGPT%20%282%29-RO7333kDslTxDVBKUYObrlbDg1DzsJ.png';
const journalImage = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Cinematic%20Trading%20Journal%20Landing%20Page-YrRnAzhVJntLnMT8hjJpygRUfttqud.png';
const features = [
  { icon: Bot, label: 'AI Agent', text: 'Extracts setup, emotion, and context from every trade.' },
  { icon: Mic, label: 'Voice Journal', text: 'Speak your trade. Get a structured journal instantly.' },
  { icon: Send, label: 'Telegram Bot', text: 'Log from Telegram wherever the trade happens.' },
  { icon: BarChart3, label: 'Smart Dashboard', text: 'See PnL, win rate, and patterns that compound.' },
  { icon: CalendarDays, label: 'Daily Summary', text: 'A quiet review of your day, delivered automatically.' },
];

function Logo() { return <div className="brand"><span className="brand-mark">∞</span><span><strong>INFINITY</strong><small>TRADER</small></span></div>; }
function NotionMark() { return <span className="notion-mark">N</span>; }
function DashboardCard() { return <div className="dashboard-card"><div className="dashboard-head"><span><span className="purple-dot">▣</span> Select<span className="purple">2</span>Notion</span><small><span className="online-dot" /> Synced to Notion <NotionMark /></small></div><div className="metric-grid">{[['Total PnL', '+$1,000.00', 'green'], ['Win Rate', '68.4%', 'green'], ['Total Trades', '32', ''], ['Profit Factor', '1.86', '']].map(([k, v, c]) => <div className="metric" key={k}><span>{k}</span><strong className={c}>{v}</strong></div>)}</div><div className="equity-panel"><div className="panel-title">Equity Curve <small>May 5 — Jun 2</small></div><svg viewBox="0 0 520 140" preserveAspectRatio="none" aria-label="Rising equity curve"><defs><linearGradient id="line" x1="0" x2="1"><stop stopColor="#7c3cff" /><stop offset="1" stopColor="#c08aff" /></linearGradient></defs><path d="M0 120 C35 105 50 125 80 100 S125 110 155 94 S185 105 215 70 S250 82 275 65 S320 76 350 50 S390 60 415 40 S460 38 520 12" fill="none" stroke="url(#line)" strokeWidth="3" /></svg></div><div className="journal-line"><span>NAS100</span><b>Long</b><strong>+$1,000.00</strong><span>Confident</span><ArrowRight size={15} /></div></div>; }
function WorkflowCard() { return <div className="workflow-card"><div className="voice-head"><span className="voice-icon"><Mic size={17} /></span><div className="wave">{Array.from({ length: 25 }, (_, i) => <i key={i} style={{ height: `${10 + (i % 6) * 5}px` }} />)}</div></div><p>Nas100 Long တယ်<br />1000$ profit ထွက်တယ်။<br />Liquidity Sweep ပြီး Entry ဝင်တယ်။</p><div className="workflow-arrow"><ArrowDown size={16} /></div></div>; }

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const nav = [['How it works', '#workflow'], ['Systems', '#systems'], ['About', '#about']];
  return <main>
    <header className="site-header"><a href="#top" aria-label="Infinity Trader home"><Logo /></a><nav>{nav.map(([label, href]) => <a key={label} href={href}>{label}</a>)}<a className="header-cta" href="https://tally.so/r/44pKVo" target="_blank" rel="noreferrer">Join waitlist <ArrowRight size={15} /></a></nav><button className="menu-button" aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></header>
    {menuOpen && <div className="mobile-nav">{nav.map(([label, href]) => <a onClick={() => setMenuOpen(false)} key={label} href={href}>{label}</a>)}<a href="https://tally.so/r/44pKVo" target="_blank" rel="noreferrer">Join waitlist <ArrowRight size={15} /></a></div>}
    <section id="top" className="hero" style={{ backgroundImage: `url(${roomImage})` }}><div className="hero-shade" /><div className="hero-content"><p className="eyebrow">TRADING JOURNAL · NOTION SYNC</p><h1>Trade first.<br /><em>Reflect after.</em></h1><p className="hero-lede">Every trade has a lesson.<br />Journaling helps you see it.</p><div className="hero-actions"><a className="button button-purple" href="https://tally.so/r/44pKVo" target="_blank" rel="noreferrer">Start journaling <ArrowRight size={17} /></a><a className="button button-ghost" href="#workflow"><Play size={15} /> See how it works</a></div></div><div className="hero-foot"><span className="mouse"><span /></span> Scroll to explore <ArrowDown size={14} /></div></section>
    <section id="workflow" className="journal-section" style={{ backgroundImage: `url(${journalImage})` }}><div className="section-shade" /><div className="journal-layout"><div className="journal-copy"><p className="eyebrow purple">VOICE → AI → NOTION</p><h2>Journal<br /><span>without</span><br />the friction.</h2><p className="section-intro">Turn a passing thought into a useful record. Select2Notion keeps the process fast enough to actually use after every trade.</p><div className="feature-list">{features.map(({ icon: Icon, label, text }) => <div className="feature" key={label}><span className="feature-icon"><Icon size={18} /></span><div><strong>{label}</strong><p>{text}</p></div></div>)}</div></div><div className="journal-product"><WorkflowCard /><div className="agent-card"><div><Bot size={16} /> AI AGENT</div>{['Trade detected', 'Data extracted', 'Emotion: Confident', 'Saved to Notion'].map(x => <p key={x}><Check size={14} /> {x}</p>)}</div><DashboardCard /></div></div></section>
    <section id="systems" className="systems-section"><div className="systems-grid" /><div className="section-inner"><div className="split-heading"><div><p className="eyebrow purple">THE METHOD</p><h2>The journal becomes<br /><span>a trading system.</span></h2></div><p>Reflection is not a post-trade ritual. It is the feedback loop that turns instinct into process.</p></div><div className="system-cards">{[['01','Capture the facts.','Record the setup, entry, risk, and outcome while the details are still clear.'],['02','Understand the pattern.','Let structure emerge from your history — not from one emotional day.'],['03','Improve with evidence.','Build a calmer, more repeatable trading practice one review at a time.']].map(([n, title, text]) => <article key={n}><span className="system-number">{n}</span><h3>{title}</h3><p>{text}</p><a href="#workflow">Explore workflow <ArrowRight size={15} /></a></article>)}</div></div></section>
    <section id="dashboard" className="dashboard-section"><div className="dashboard-copy"><p className="eyebrow purple">YOUR EDGE, VISIBLE</p><h2>See what your<br /><span>trades are teaching you.</span></h2><p>Not another place to collect numbers. A private workspace for the decisions behind them.</p><ul>{['One-click Notion sync', 'Voice and Telegram capture', 'Performance summaries that matter'].map(x => <li key={x}><Check size={16} /> {x}</li>)}</ul><a className="button button-purple" href="https://tally.so/r/44pKVo" target="_blank" rel="noreferrer">Get early access <ArrowRight size={17} /></a></div><DashboardCard /></section>
    <section id="about" className="about-section"><p className="eyebrow purple">FOR THE LONG GAME</p><h2>Trade with intention.<br /><span>Review with honesty.</span></h2><p>Built for traders who know that consistency is not a personality trait. It is a system you can practice.</p><a className="button button-purple" href="mailto:iinfinitytraders@gmail.com">Talk to us <ArrowRight size={17} /></a></section>
    <footer><Logo /><span>© 2026 Infinity Trader · Select2Notion</span><a href="mailto:iinfinitytraders@gmail.com">iinfinitytraders@gmail.com</a></footer>
  </main>;
}
